### ISSUE TITLE
Cannot find geometric reprojection error code

### ISSUE THREAD

**Issue by WoojunePark** [GrumpyZhou/visloc-apr#2]
Hi!

I could easily find implementations for position/rotation errors (loss_xyz, loss_wpqr) and learned optimal weighting from 3.3.1 ~ 3.3.3 of 'Geometric Loss Functions for Camera Pose Regression With Deep Learning'.

but I cannot find the code for geometric reprojection error from 3.3.4 of the same paper. 

Am I missing something? :(

**Comment by GrumpyZhou** [comment]
Hi @WoojunePark ,  

I didn't put codes for the geometric reprojection loss since it was not working less effectively than the learned weighting in our experiments. And this also requires different data loading since you will need a set of 3D points to perform the reprojection. 
It was an old project, I don't have my old implementations anymore. If you want to investigate this loss, you will need to implement it yourself.
